name: chessground_game_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  # sdk: ">=2.18.0 <3.9.0"
  sdk: ^3.9.0
  # sdk: ^3.8.1  

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  chessground: ^7.1.6
    # path: ../
  dartchess: ^0.11.1
  fast_immutable_collections: ^11.0.0
  get: ^4.7.2
  chess_vectors_flutter: ^1.1.0
  sound_effect: ^0.1.1
  # stockfish_chess_engine: ^0.8.2
  # 
  stockfish: ^1.7.1
  # 
  # multistockfish: ^0.3.0
  # multistockfish_chess: ^0.2.1
  # multistockfish_sf16: ^0.1.1
  # multistockfish_variant: ^0.1.1
  # 
  # editable_chess_board: ^0.5.2
  # window_manager: ^0.5.1
  # simple_chess_board: ^1.7.1
  material_design_icons_flutter: ^7.0.7296
  isar: ^3.1.0+1
  isar_flutter_libs:
    git: 
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git

  path_provider: ^2.1.5
  uuid: ^4.5.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  l10n_esperanto: ^2.0.13
  material_symbols_icons: ^4.2874.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.2
  freezed_annotation: any
  # freezed_annotation: ^3.2.3
  json_annotation: ^4.9.0
  pull_to_refresh: ^2.0.0
  flutter_chess_board: ^1.0.1
  editable_chess_board: ^0.1.4
  deep_pick: ^1.1.0
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.3.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  dynamic_system_colors: ^1.8.0
  share_plus: ^12.0.1
  fl_chart: ^1.1.1
  # flutter_local_notifications: ^19.5.0
  # meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  mocktail: ^1.0.4
  flutter_lints: ^ 5.0.0
  freezed: any
  # freezed: ^3.2.3
  build_runner: any
  # build_runner: ^2.10.1
  json_serializable: any
  # json_serializable: ^6.11.1
  # freezed_lint: ^0.0.12
  # isar_generator: ^3.1.0+1
  isar_generator: any
  fake_async: ^1.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/futuristic/
    - assets/sounds/lisp/
    - assets/sounds/nes/
    - assets/sounds/piano/
    - assets/sounds/standard/
    - assets/sounds/sfx/
  #   - images/a_dot_ham.jpeg
flutter_assets:
  assets_path: assets/sounds/
  output_path: lib/core/constants/
  filename: app_images_sounds.dart
  field_prefix: 
  



# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   flutter_lints: ^5.0.0

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true